{% set version = '2.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeest/modeest_{{ version }}.tar.gz
  sha256: 36cab5a2a7b521bd58a71557a74be8d0f3a0ea6c86a18f863aa95e0841fc33f9

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bazar
    - r-fbasics
    - r-genefilter
    - r-stable
    - r-stabledist
    - r-statip
  run:
    - r-base
    - r-bazar
    - r-fbasics
    - r-genefilter
    - r-stable
    - r-stabledist
    - r-statip

test:
  commands:
    - $R -e "library('modeest')"           # [not win]
    - "\"%R%\" -e \"library('modeest')\""  # [win]

about:
  home: https://github.com/paulponcet/modeest
  license: GPL-3
  summary: 'Provides estimators of the mode of univariate data or univariate distributions. '
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: modeest
# Type: Package
# Title: Mode Estimation
# Version: 2.3.3
# Date: 2019-03-13
# Authors@R: person("Paul", "Poncet", , "paulponcet@yahoo.fr", role = c("aut", "cre"))
# Description: Provides estimators of the mode of univariate data or univariate distributions.
# License: GPL-3
# LazyData: TRUE
# Depends: R (>= 3.1.3)
# Imports: bazar, fBasics, genefilter, stable, stabledist, stats, statip
# Suggests: evd, knitr, mvtnorm, testthat, VGAM
# URL: https://github.com/paulponcet/modeest
# BugReports: https://github.com/paulponcet/modeest/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-13 21:05:59 UTC; YL1101
# Author: Paul Poncet [aut, cre]
# Maintainer: Paul Poncet <paulponcet@yahoo.fr>
# Repository: CRAN
# Date/Publication: 2019-03-13 22:00:03 UTC
