{% set version = "2.4.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeest
  version: {{ version|replace("-", "_") }}

source:
  fn: modeest_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/modeest_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/modeest/modeest_{{ version }}.tar.gz

  sha256: 1a949409bf64679d32400d20aa3d53e65a9a20f5bd1a40993b95f81100e0ed20

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-fbasics
    - r-stable
    - r-stabledist
    - r-statip >=0.2.3
  run:
    - r-base
    - r-fbasics
    - r-stable
    - r-stabledist
    - r-statip >=0.2.3

test:
  commands:
    - $R -e "library('modeest')"  # [not win]
    - "\"%R%\" -e \"library('modeest')\""  # [win]

about:
  home: https://github.com/paulponcet/modeest
  license: GPL-3
  summary: Provides estimators of the mode of univariate data or univariate distributions.
  license_family: GPL-3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
   recipe-maintainers:
    - conda-forge/r
