travis:
  secure:
    BINSTAR_TOKEN: Oes8v9cd7+b6RZ74U/HNWy3Kk2q4i/mx6xNzhikDQeuJy00Yl+SEXbOcQrkr5zB6Nz3gYzCxhP9kWEplamNZuKwlj/BRe1fDk0p82JBKsgkWpAZRfJlm0s7T9oe6qqbfPVhmvHSskFxxCvGXfQtwzxrRRWVlPqqGFZ6+eOUIij0w/UEISH+XxUT/egpYlXPsxYT0ZKMnz9r34OmmFw+eOE/tZC49SqjoWjvtPR/UpQs40YiITyRiBuOkPVdwo8S2EraGrmtR6MT2DeoEjjPHq8lDOhz0gAeIKR/7dxsmGEc6G48bFfoONp+yKiVRnBEdif5CU7N2I4FAwy8fnTVfm8gNwQo88oLN3PcL2bskzPTaukbYLoVPlksDfr1LjGJwXN2chPscv+PGIO7RyQtgBY3wPUZ3yLV7zII7X8yPnRPxvzKU3Ou4Gw0NIgOzgArXau00VekUjIgVLs4N+RVMFehxDxKkp/Npgdc3WpSMa0nxXNAInN7qpQn+g6OCFxNEhpDXQoxbbUAQlMZKRFAwOQ4XHCcnN+kAXjUwAj/djjyadWAw0hv4q8B6UgLUQbJLpc9tEl/7I9lZ5WR0zDoAkU4OSBhnMRfZDBgyD9drvmb7ixFrWyNOkTEyxnU/Nv7v+eCzvI8bJCrNwnWb813MkqzEY+Z71aCkFiGOeFOMmOk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
