travis:
  secure:
    BINSTAR_TOKEN: rGuK4ICfYPz0yrXVU98/sK7f8L3Cf+g+xW3N1+7PmvhdNBntd01BJ74w8UvQwijQyd6mQw5XydLeWZL5apIYOUbCVGqOIRy3kBgFdUohpF16YqrWvTfFyD3ZbNitbcCqKOR1mIxpv9joMx0jTNr7BANRdVLRCsQB8BH1fcIz7QnN2qAfbC+655ECRJdIBPW+OBWtSQu3/2CnwMlxqqL2q+xROGEPM4daP7rx03PsV7y6zMzn0AV4trg8fwOuZ3GUvgGoCS6PgL1e56YLYRchQtis+L51HKYF5y8ciiPV62/dWs6bAy0+SXCU+RKGIQmTVtu3d7EvSjDekkGlIvjPFqNNcL9m7RW/i1eAISFe0bJCFbgwsKJaxHKftcbOmMqo6MAkt1OnDUmP0u3161YpBFB0Ne4k+eLUbB6I/fHn32uqMzWZNgkOuz7lcmH1z9pcqIhnbMg5Z5bXKvIeOClKxRriqXd8QCkGeE5jTR+X0ZuYHZufXjxybAasStcU71Qb3eMz6NBfrXgdllNVUYA51uV1TKd1mSDRP7HoYPu9vZIhP1s0wF6nmrrY1TumDulbTu1CP3ngt49dASQeKjCFB4EmMl3bpqmXFDMYKlzZfMkvMEmq0QhevvIPdQnjj6WDyvrGk2rhnLw1L5zH/8S5MAxsW+14+ukHoXDfF7/cGRk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
