appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: p9ljwvRfJ4SVvzUka1Cg3Ih12OJo9RbBY249o+oce3HKPq28qD5qsWKksio7FsVEXplZ1xVQd1/eBxTX7Z0sOmVmj0cbn3s8TSFOLTvyDJE8a/TsRTFln/7NSIlRFB/kVjK+EErbVFxCR0vlVjcFIcIvqrwCzy6nO2WpNCLnlDXywc6ALyvY5nvCdun4PH6f5FmZ0DuJclI9JcDkuKwChYH0BmT8+so343acHXnLc77o0NP03hCWXeZJIFM/g1LGlOZ0ICRkkaPpygCzKYA10kIvgSRtaVZuGoh+0o9ubj9EEboCeGfVncBAMswauFrYsgniDXw7tvS3pDWJz1EFtR6O7TAxIuUtG9KsxYtf1PpbVv7aqXlZC9sEaqD/copzmY/Jx6ynBRg4H3YikCyaGbiUHTvVGyKjJpIxtod3oJqA2Zdt1SjO3+KdX/raKq0zzDpYMKefBIvZOkoKsCPE4xU0/X6ZutBqLBwDjh9uyFbnx1mZOgM/nM7+uYNpR75Q4Qn+meQnd/oPQJKMkobCzPycuc6OwEMH1vcpyyzpSGs2iiUGpYe/jQMgXMNkpyxyf7X4wE5xcPpP1MQSJhVddtw1Q522eoBdJXNxDbUooQPJKeX+vZp/nPgiDL6RnB0MZO0BhybsjDVfxWpSCJZUV9SP+MPIKEoOfyrR9/4OyEw=
